version: '3'

services:
    webservice:
        image: bottle
        build: .
        command: sh -c "flask db upgrade && gunicorn -b 0.0.0.0:5000 bottle.wsgi:app"
        env_file:
            - production.env
        ports:
            - "5000:5000"